FROM python:3.10-slim

# Instala dependências do sistema
RUN apt-get update && apt-get install -y \
    wget curl gnupg2 \
    libglib2.0-0 libnss3 libgconf-2-4 \
    libatk1.0-0 libatk-bridge2.0-0 libcups2 \
    libxcomposite1 libxdamage1 libxrandr2 \
    libasound2 libpangocairo-1.0-0 \
    libxss1 libxtst6 libgtk-3-0 xvfb \
    && rm -rf /var/lib/apt/lists/*

# Instala Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instala o navegador Playwright
RUN playwright install --with-deps

# Copia o app
COPY . /app
WORKDIR /app

CMD ["python", "app.py"]
